services:
  - type: web
    name: personal-finance-manager-pro
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn controller:app --bind 0.0.0.0:$PORT --workers 2"
    plan: starter
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DEBUG
        value: false

databases:
  - name: finance-manager-db
    plan: starter
